

services:
  pheme:
    build: .
    platform: linux/amd64
    ports:
      - "8025:8000"
    volumes:
      - .:/app
    environment:
      - PHEME_HOST=0.0.0.0
      - PHEME_PORT=8000
      - HUGGING_FACE_HUB_TOKEN=${HUGGING_FACE_HUB_TOKEN}
      - PHONEMIZER_ESPEAK_LIBRARY=${PHONEMIZER_ESPEAK_LIBRARY}